backend:
  name: github
  repo: Eltee/eltee.github.io
  branch: main
  automatic_deployments: false
  use_graphql: true
  site_domain: 719c9922-ec6c-4154-a82d-5452783370bc
  squash_merges: true
site_url: https://eltee.online
publish_mode: editorial_workflow
show_preview_links: true
media_folder: static/images/uploads
public_folder: /images/uploads
collections:
  - name: 'completed'
    label: 'Completed Games'
    folder: 'content/completed'
    create: true
    preview_path: completed/{{slug}}
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Completed Date', name: 'date', widget: 'datetime', default: '{{now}}' }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Type', name: 'type', widget: 'select', options: ["post"], default: "post" }
      - { label: 'Link Image', name: 'image', widget: 'image', choose_url: true, required: false }
      - { label: 'Tags', name: 'tags', widget: 'list', allow_add: true, required: false }
      - { label: 'Show Table of Contents', name: 'showTableOfContents', widget: 'boolean', default: false }
      - { label: 'Author', name: 'params.author', widget: string, default: 'Eltee' }
      - { label: 'Category', name: 'params.category', widget: select, options: ["Completed", "Misc", "Nextfest", "VGM", "YouTube"], default: "Completed" }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'misc'
    label: 'Miscellaneous'
    folder: 'content/misc'
    create: true
    preview_path: misc/{{slug}}
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publication Date', name: 'date', widget: 'datetime', default: '{{now}}' }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Type', name: 'type', widget: 'select', options: ["post"], default: "post" }
      - { label: 'Link Image', name: 'image', widget: 'image', choose_url: true, required: false }
      - { label: 'Tags', name: 'tags', widget: 'list', allow_add: true, required: false }
      - { label: 'Show Table of Contents', name: 'showTableOfContents', widget: 'boolean', default: false }
      - { label: 'Author', name: 'params.author', widget: string, default: 'Eltee' }
      - { label: 'Category', name: 'params.category', widget: select, options: ["Completed", "Misc", "Nextfest", "VGM", "YouTube"], default: "Completed" }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'nextfest'
    label: 'Steam Nextfest'
    folder: 'content/nextfest'
    create: true
    preview_path: nextfest/{{slug}}
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Nextfest Date', name: 'date', widget: 'datetime', default: '{{now}}' }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Type', name: 'type', widget: 'select', options: ["post"], default: "post" }
      - { label: 'Link Image', name: 'image', widget: 'image', choose_url: true, required: false }
      - { label: 'Tags', name: 'tags', widget: 'list', allow_add: true, required: false }
      - { label: 'Show Table of Contents', name: 'showTableOfContents', widget: 'boolean', default: false }
      - { label: 'Author', name: 'params.author', widget: string, default: 'Eltee' }
      - { label: 'Category', name: 'params.category', widget: select, options: ["Completed", "Misc", "Nextfest", "VGM", "YouTube"], default: "Completed" }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'vgm'
    label: 'VGM Showcase'
    folder: 'content/vgm'
    create: true
    preview_path: vgm/{{slug}}
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publication Date', name: 'date', widget: 'datetime', default: '{{now}}' }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Type', name: 'type', widget: 'select', options: ["post"], default: "post" }
      - { label: 'Link Image', name: 'image', widget: 'image', choose_url: true, required: false }
      - { label: 'Tags', name: 'tags', widget: 'list', allow_add: true, required: false }
      - { label: 'Show Table of Contents', name: 'showTableOfContents', widget: 'boolean', default: false }
      - { label: 'Author', name: 'params.author', widget: string, default: 'Eltee' }
      - { label: 'Category', name: 'params.category', widget: select, options: ["Completed", "Misc", "Nextfest", "VGM", "YouTube"], default: "Completed" }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'youtube'
    label: 'YouTube'
    folder: 'content/youtube'
    create: true
    preview_path: youtube/{{slug}}
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Video Date', name: 'date', widget: 'datetime', default: '{{now}}' }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Type', name: 'type', widget: 'select', options: ["post"], default: "post" }
      - { label: 'Link Image', name: 'image', widget: 'image', choose_url: true, required: false }
      - { label: 'Tags', name: 'tags', widget: 'list', allow_add: true, required: false }
      - { label: 'Show Table of Contents', name: 'showTableOfContents', widget: 'boolean', default: false }
      - { label: 'Author', name: 'params.author', widget: string, default: 'Eltee' }
      - { label: 'Category', name: 'params.category', widget: select, options: ["Completed", "Misc", "Nextfest", "VGM", "YouTube"], default: "Completed" }
      - { label: 'Body', name: 'body', widget: 'markdown' }
